name: Merge demo Sopra
run-name: Nornir diff - Merge push

on: 
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  merge_diff:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          repository: edudppaz/iac-demo
          path: napalm_script
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment (Python)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Running script in push mode
        id: diff-merge
        run: |
          python napalm_example2.py --diff --force >> merge.txt
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "merge<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat merge.txt)." >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      
      # Add diff result as comment
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ### Push result 
            ```
            ${{steps.diff-merge.outputs.merge}}
            ```
            ### End push result
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default