name: PR demo Sopra
run-name: Nornir diff - PR show

on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  generate_config_and_diff:
    runs-on: self-hosted
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          repository: edudppaz/iac-demo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment (Python)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Running script in diff mode
        id: diff-run
        run: |
          python napalm_example2.py --diff >> diff.txt
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "diff<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat diff.txt)." >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      
      # Add diff result as comment
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ### Diff result 
            ```
            ${{steps.diff-run.outputs.diff}}
            ```
            ### End diff result
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default